
logging.path: /var/log/gg/nttoa-welcome-api

spring:
  thymeleaf.cache: false

server:
  tomcat:
    basedir: /opt/nttoa-welcome-api/tomcat
    accesslog:
      directory: ${logging.path}/tomcat
      prefix: nttoa-welcome-api_access_log
      enabled: false
      pattern: "%t %a %{Trace-Id}i \"%r\" %s (%D ms)"
  port: 8099
  ssl:
    enabled: false
    key-alias:
    key-password:
    key-store:
    key-store-password:
    trust-store:
    trust-store-password:
    client-auth:
  servlet:
    context-path: /
security:
  oauth2:
    resource:
      id: nttoa-welcome-api
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

build.info.file: classpath:build-info.yml


jasypt:
  keystore: classpath:certs/jasyptKeystore.jks
  keystore-passwd: lAnJIIln8cNL6W88cTrSS7/1BDcfWaqeyM1JODpH9GM
  alias: jasypt

management:
  #    security.flag: false
  server:
    add-application-context-header: false
  #      servlet:
  #        context-path: /
  endpoints:
    enabled-by-default: false
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

swagger:
  api:
    title: nttoa-welcome-api
    contact.info: The giffgaff Platform Team
    licence.url: #
    description:
    groupName: nttoa-welcome-api
    version: 2.0
  terms.of.service.url: #
  enabled: true

microservice:
  aws:
    secretsmanager:
      enabled: false
  build:
    info:
      file: classpath:build-info.yml
  rest:
    logging:
      enabled: false
      verbose: false
      secure:
        enabled: false
        key:
        salt:
    internal-client:
      oauth2:
        enabled: false
        client-id:
        client-secret:
        access-token-uri: https://id.giffgaff.com/auth/oauth/token
      x509:
        enabled: false
        key-password: ${server.ssl.key-password}
        key-store: ${server.ssl.key-store}
        key-store-password: ${server.ssl.key-store-password}
        trust-store: ${server.ssl.trust-store}
        trust-store-password: ${server.ssl.trust-store-password}
